In [1]:
import pandas as pd

# df = pd.read_json("data/results_prwp_batch1.jsonl", lines=True)
df = pd.read_json("data/results_refugee_batch1.jsonl", lines=True)
df

,snapshot_id,image_path,source_label,llm_output,raw_output,usage,cost,error
0,112_IDAR2016-0221-PAD-09012016_table_007.png,data/refugee_batch1/112_IDAR2016-0221-PAD-0901...,Refugee,{'visible_text_label': 'Consultancy Assignment...,"```json\n{\n ""visible_text_label"": ""Consultan...","{'input_tokens': 26304, 'input_tokens_details'...","{'input_tokens': 26304, 'output_tokens': 121, ...",NaN
1,056_Niger-COVID-19-Emergency-Response-Project_...,data/refugee_batch1/056_Niger-COVID-19-Emergen...,Refugee,"{'visible_text_label': 'Figure 1: Countries, t...","{\n ""visible_text_label"": ""Figure 1: Countrie...","{'input_tokens': 37607, 'input_tokens_details'...","{'input_tokens': 37607, 'output_tokens': 142, ...",NaN
2,194_multi-page_figure_000.png,data/refugee_batch1/194_multi-page_figure_000.png,Refugee,{'visible_text_label': 'Annex 10: Country at a...,"```json\n{\n ""visible_text_label"": ""Annex 10:...","{'input_tokens': 37681, 'input_tokens_details'...","{'input_tokens': 37681, 'output_tokens': 162, ...",NaN
3,069_Pakistan-Strengthening-Institutions-for-Re...,data/refugee_batch1/069_Pakistan-Strengthening...,Refugee,{'visible_text_label': 'Project Development Ob...,"{\n ""visible_text_label"": ""Project Developmen...","{'input_tokens': 49016, 'input_tokens_details'...","{'input_tokens': 49016, 'output_tokens': 118, ...",NaN
4,202_multi0page_table_007.png,data/refugee_batch1/202_multi0page_table_007.png,Refugee,{'visible_text_label': 'Annex 6 El Nino Emerge...,"```json\n{\n ""visible_text_label"": ""Annex 6\n...","{'input_tokens': 37654, 'input_tokens_details'...","{'input_tokens': 37654, 'output_tokens': 141, ...",NaN
5,203_multi-page_table_006.png,data/refugee_batch1/203_multi-page_table_006.png,Refugee,{'visible_text_label': 'Table C: Allocation of...,"{\n ""visible_text_label"": ""Table C: Allocatio...","{'input_tokens': 26278, 'input_tokens_details'...","{'input_tokens': 26278, 'output_tokens': 111, ...",NaN
6,197_multi-page_table_000.png,data/refugee_batch1/197_multi-page_table_000.png,Refugee,"{'visible_text_label': 'Component', 'data_moda...","{\n ""visible_text_label"": ""Component"",\n ""da...","{'input_tokens': 48968, 'input_tokens_details'...","{'input_tokens': 48968, 'output_tokens': 116, ...",NaN
7,189_multi-page_table_012.png,data/refugee_batch1/189_multi-page_table_012.png,Refugee,"{'visible_text_label': 'none', 'data_modality'...","```json\n{\n ""visible_text_label"": ""none"",\n ...","{'input_tokens': 26249, 'input_tokens_details'...","{'input_tokens': 26249, 'output_tokens': 117, ...",NaN
8,199_multi0page_table_004.png,data/refugee_batch1/199_multi0page_table_004.png,Refugee,{'visible_text_label': 'Project Cost and Finan...,"{\n ""visible_text_label"": ""Project Cost and F...","{'input_tokens': 37604, 'input_tokens_details'...","{'input_tokens': 37604, 'output_tokens': 114, ...",NaN
9,191_multi-page_figure_000.png,data/refugee_batch1/191_multi-page_figure_000.png,Refugee,"{'visible_text_label': 'Burundi at a glance', ...","{\n ""visible_text_label"": ""Burundi at a glanc...","{'input_tokens': 37610, 'input_tokens_details'...","{'input_tokens': 37610, 'output_tokens': 140, ...",NaN
10,121_PAD1190-PAD-P152848-PUBLIC-Box391435B-LB-E...,data/refugee_batch1/121_PAD1190-PAD-P152848-PU...,Refugee,{'visible_text_label': 'Table 3: Procurement o...,"{\n ""visible_text_label"": ""Table 3: Procureme...","{'input_tokens': 48906, 'input_tokens_details'...","{'input_tokens': 48906, 'output_tokens': 125, ...",NaN
11,203_multi-page_table_009.png,data/refugee_batch1/203_multi-page_table_009.png,Refugee,{'visible_text_label': 'Jordan STATEMENT OF IF...,"{\n ""visible_text_label"": ""Jordan STATEMENT O...","{'input_tokens': 37612, 'input_tokens_details'...","{'input_tokens': 37612, 'output_tokens': 149, ...",NaN
12,074_Djibouti-Integrated-Cash-Transfer-and-Huma...,data/refugee_batch1/074_Djibouti-Integrated-Ca...,Refugee,{'visible_text_label': 'Beneficiaries with acc...,"{\n ""visible_text_label"": ""Beneficiaries with...","{'input_tokens': 26319, 'input_tokens_details'...","{'input_tokens': 26319, 'output_tokens': 128, ...",NaN
13,014_BOSIB1dda1d49e0221807413cf06ea9ae3f_table_...,data/refugee_batch1/014_BOSIB1dda1d49e02218074...,Refugee,{'visible_text_label': '1 : FIGA is reformed i...,"{\n ""visible_text_label"": ""1 : FIGA is reform...","{'input_tokens': 26298, 'input_tokens_details'...","{'input_tokens': 26298, 'output_tokens': 180, ...",NaN
14,193_multi-page_table_010.png,data/refugee_batch1/193_multi-page_table_010.png,Refugee,{'visible_text_label': 'STATEMENT OF IFC's Com...,"{\n ""visible_text_label"": ""STATEMENT OF IFC's...","{'input_tokens': 37569, 'input_tokens_details'...","{'input_tokens': 37569, 'output_tokens': 150, ...",NaN
15,194_multi-page_table_000.png,data/refugee_batch1/194_multi-page_table_000.png,Refugee,{'visible_text_label': '1. Project components ...,"```json\n{\n ""visible_text_label"": ""1. Projec...","{'input_tokens': 26347, 'input_tokens_details'...","{'input_tokens': 26347, 'output_tokens': 154, ...",NaN
16,191_multi-page_table_006.png,data/refugee_batch1/191_multi-page_table_006.png,Refugee,{'visible_text_label': 'TABLE A: PROJECT COSTS...,"{\n ""visible_text_label"": ""TABLE A: PROJECT C...","{'input_tokens': 26276, 'input_tokens_details'...","{'input_tokens': 26276, 'output_tokens': 127, ...",NaN
17,006_BOSIB-2c22668f-f4ba-42f5-a0d1-7949b7b8fe34...,data/refugee_batch1/006_BOSIB-2c22668f-f4ba-42...,Refugee,{'visible_text_label': 'Enhanced production an...,"{\n ""visible_text_label"": ""Enhanced productio...","{'input_tokens': 49009, 'input_tokens_details'...","{'input_tokens': 49009, 'output_tokens': 108, ...",NaN
18,004_BOSIB-87c444de-4797-4bf9-b654-4932a7fb0112...,data/refugee_batch1/004_BOSIB-87c444de-4797-4b...,Refugee,"{'visible_text_label': 'IDA Resources (US$, Mi...","{\n ""visible_text_label"": ""IDA Resources (US$...","{'input_tokens': 37431, 'input_tokens_details'...","{'input_tokens': 37431, 'output_tokens': 121, ...",NaN
19,202_multi0page_table_008.png,data/refugee_batch1/202_multi0page_table_008.png,Refugee,{'visible_text_label': 'Uganda STATEMENT OF IF...,"```json\n{\n ""visible_text_label"": ""Uganda ST...","{'input_tokens': 26320, 'input_tokens_details'...","{'input_tokens': 26320, 'output_tokens': 148, ...",NaN
20,191_multi-page_table_000.png,data/refugee_batch1/191_multi-page_table_000.png,Refugee,{'visible_text_label': 'Project Financing Data...,"```json\n{\n ""visible_text_label"": ""Project F...","{'input_tokens': 26276, 'input_tokens_details'...","{'input_tokens': 26276, 'output_tokens': 115, ...",NaN
21,200_multi-page_table_014.png,data/refugee_batch1/200_multi-page_table_014.png,Refugee,{'visible_text_label': 'Table C: Allocation of...,"{\n ""visible_text_label"": ""Table C: Allocatio...","{'input_tokens': 48943, 'input_tokens_details'...","{'input_tokens': 48943, 'output_tokens': 117, ...",NaN
22,193_multi-page_table_007.png,data/refugee_batch1/193_multi-page_table_007.png,Refugee,"{'visible_text_label': 'Annex 4, Table D: Allo...","{\n ""visible_text_label"": ""Annex 4, Table D: ...","{'input_tokens': 37569, 'input_tokens_details'...","{'input_tokens': 37569, 'output_tokens': 125, ...",NaN
23,193_multi-page_table_006.png,data/refugee_batch1/193_multi-page_table_006.png,Refugee,"{'visible_text_label': 'Annex 4, Table C: Summ...","{\n ""visible_text_label"": ""Annex 4, Table C: ...","{'input_tokens': 37569, 'input_tokens_details'...","{'input_tokens': 37569, 'output_tokens': 118, ...",NaN
24,199_multi0page_table_001.png,data/refugee_batch1/199_multi0page_table_001.png,Refugee,{'visible_text_label': '1. Project components ...,"```json\n{\n ""visible_text_label"": ""1. Projec...","{'input_tokens': 26270, 'input_tokens_details'...","{'input_tokens': 26270, 'output_tokens': 141, ...",NaN
25,121_PAD1190-PAD-P152848-PUBLIC-Box391435B-LB-E...,data/refugee_batch1/121_PAD1190-PAD-P152848-PU...,Refugee,{'visible_text_label': 'Category Amount of the...,"{\n ""visible_text_label"": ""Category\nAmount o...","{'input_tokens': 37572, 'input_tokens_details'...","{'input_tokens': 37572, 'output_tokens': 136, ...",NaN
26,189_multi-page_figure_001.png,data/refugee_batch1/189_multi-page_figure_001.png,Refugee,{'visible_text_label': 'PRICES and GOVERNMENT ...,"```json\n{\n ""visible_text_label"": ""PRICES an...","{'input_tokens': 26249, 'input_tokens_details'...","{'input_tokens': 26249, 'output_tokens': 135, ...",NaN
27,091_PAD2604-ARABIC-PUBLIC-Project-Appraisal-Do...,data/refugee_batch1/091_PAD2604-ARABIC-PUBLIC-...,Refugee,{'visible_text_label': '4.7 موجز التحليلي (بال...,"```json\n{\n ""visible_text_label"": ""4.7 موجز ...","{'input_tokens': 48923, 'input_tokens_details'...","{'input_tokens': 48923, 'output_tokens': 138, ...",NaN
28,054_Sudan-Basic-Education-Emergency-Support-Pr...,data/refugee_batch1/054_Sudan-Basic-Education-...,Refugee,"{'visible_text_label': 'Team', 'data_modality'...","```json\n{\n ""visible_text_label"": ""Team"",\n ...","{'input_tokens': 48847, 'input_tokens_details'...","{'input_tokens': 48847, 'output_tokens': 111, ...",NaN
29,004_BOSIB-87c444de-4797-4bf9-b654-4932a7fb0112...,data/refugee_batch1/004_BOSIB-87c444de-4797-4b...,Refugee,{'visible_text_label': 'PDO Indicators by PDO ...,"{\n ""visible_text_label"": ""PDO Indicators by ...","{'input_tokens': 37431, 'input_tokens_details'...","{'input_tokens': 37431, 'output_tokens': 111, ...",NaN
30,193_multi-page_figure_001.png,data/refugee_batch1/193_multi-page_figure_001.png,Refugee,"{'visible_text_label': 'Tajikistan', 'data_mod...","{\n ""visible_text_label"": ""Tajikistan"",\n ""d...","{'input_tokens': 37569, 'input_tokens_details'...","{'input_tokens': 37569, 'output_tokens': 122, ...",NaN
31,005_BOSIB-8191b179-7209-4faa-b5e0-11783bcd492d...,data/refugee_batch1/005_BOSIB-8191b179-7209-4f...,Refugee,{'visible_text_label': 'Microcredentials firm ...,"{\n ""visible_text_label"": ""Microcredentials f...","{'input_tokens': 26291, 'input_tokens_details'...","{'input_tokens': 26291, 'output_tokens': 166, ...",NaN
32,203_multi-page_figure_003.png,data/refugee_batch1/203_multi-page_figure_003.png,Refugee,{'visible_text_label': 'JORDAN COMMUNITY INFRA...,"{\n ""visible_text_label"": ""JORDAN COMMUNITY I...","{'input_tokens': 37612, 'input_tokens_details'...","{'input_tokens': 37612, 'output_tokens': 133, ...",NaN
33,040_Iraq-COVID-19-Vaccination-Project_table_00...,data/refugee_batch1/040_Iraq-COVID-19-Vaccinat...,Refugee,{'visible_text_label': 'Table 5: Project Cost ...,"```json\n{\n ""visible_text_label"": ""Table 5: ...","{'input_tokens': 48918, 'input_tokens_details'...","{'input_tokens': 48918, 'output_tokens': 117, ...",NaN
34,121_PAD1190-PAD-P152848-PUBLIC-Box391435B-LB-E...,data/refugee_batch1/121_PAD1190-PAD-P152848-PU...,Refugee,{'visible_text_label': 'Table 1: Implementatio...,"```json\n{\n ""visible_text_label"": ""Table 1: ...","{'input_tokens': 37572, 'input_tokens_details'...","{'input_tokens': 37572, 'output_tokens': 127, ...",NaN

In [2]:
pd.json_normalize(df["cost"])["total_cost_usd"].sum()

np.float64(0.19334899999999997)

In [3]:
pd.json_normalize(df["llm_output"])

,visible_text_label,data_modality,topic_domain,population,geographic_scope,temporal_aspect,measurement_units,short_description
0,Consultancy Assignments with Selection Methods...,administrative counts,urban development,unclear,West Bank and Gaza,unclear,USD ($000),The table lists various consultancy assignment...
1,"Figure 1: Countries, territories or areas with...",geospatial distribution,health,unclear,global,specific date (24 March 2020),counts,The figure displays a world map indicating cou...
2,Annex 10: Country at a Glance\nWEST BANK AND G...,key economic ratios and demographic indicators,"poverty and social conditions, economic develo...",general population,West Bank and Gaza,single year (1997),"counts, percentages, USD billions",The snapshot reports on various socio-economic...
3,Project Development Objective Indicators,performance indicators,refugee management,refugees,Pakistan,unclear,"percentages, counts",The table outlines project development objecti...
4,Annex 6\nEl Nino Emergency Road Repair Project...,administrative counts,infrastructure rehabilitation,unclear,Uganda,specific dates and planned timelines,"US dollars, months, specific dates",The snapshot contains a project budget and sch...
5,Table C: Allocation of Loan Proceeds,financial allocation,infrastructure development,unclear,unclear,unclear,"US$ million, percentage",The table reports the allocation of loan proce...
6,Component,budget allocation,community development,unclear,Rwanda,unclear,US$ million,The table reports the budget allocation for va...
7,none,administrative counts,infrastructure repair,unclear,Albania,unclear,monetary values (in currency),The table reports various road repair projects...
8,Project Cost and Financing Plan,financial reporting,infrastructure development,unclear,Croatia,multi-year trend,DEM million,The snapshot presents data on project costs an...
9,Burundi at a glance,statistical data,socio-economic indicators,unclear,Burundi,single year (1997) and historical data from 19...,"various (millions, percentages, ratios, US dol...",The snapshot provides various socio-economic i...
10,Table 3: Procurement of major Goods and Works ...,administrative counts,education,unclear,Lebanon,specific project duration,"USD, months",The table reports on the procurement of major ...
11,Jordan STATEMENT OF IFC's Committed and Disbur...,administrative counts,infrastructure financing,companies,Jordan,single date,millions of USD,The table reports on the committed and disburs...
12,Beneficiaries with access to basic services in...,monitoring indicators,basic services,beneficiaries,unclear,unclear,counts,The table reports the baseline and end target ...
13,1 : FIGA is reformed in a manner satisfactory ...,administrative counts,livelihoods,MSMEs,Burundi,unclear,USD,The table reports on the reform status of FIGA...
14,STATEMENT OF IFC's Committed and Disbursed Por...,financial reporting,economic investment,companies,Tajikistan,specific date,millions of US dollars,The table reports the committed and disbursed ...
15,1. Project components (see Annex 2 for a detai...,administrative counts,"infrastructure, social services","local government units (LGUs), local contracto...",West Bank and Gaza,unclear,"USD million (US$M), percentages",The table presents the indicative costs and fi...
16,TABLE A: PROJECT COSTS BY PROCUREMENT ARRANGEM...,administrative counts,project costs,unclear,Burundi,unclear,million US dollars,The table reports the costs associated with va...
17,Enhanced production and income generation amon...,counts,livelihoods,"farmers, including female farmers",unclear,multi-year trend,Number,The table reports the number of farmers and fe...
18,"IDA Resources (US$, Millions)",financial allocations,funding mechanisms,unclear,Djibouti,multi-year trend,millions of USD,This table reports financial allocations from ...
19,Uganda STATEMENT OF IFC's Committed and Disbur...,financial reporting,infrastructure financing,companies,Uganda,single year,US dollar millions,The table reports the committed and disbursed ...
20,Project Financing Data,project financing details,"community development, social assistance",unclear,Burundi,multi-year trend,US dollars,The table presents financing details for the S...
21,Table C: Allocation of Loan Proceeds,financial allocation,infrastructure and environmental protection,unclear,Croatia,unclear,US $million,The table details the allocation of loan proce...
22,"Annex 4, Table D: Allocation of Loan Proceeds",financial allocations,education,unclear,Tajikistan,unclear,US$ million,The table presents the allocation of loan proc...
23,"Annex 4, Table C: Summary of Procurement Activ...",administrative counts,education,unclear,Tajikistan,unclear,monetary values (million USD),The table summarizes procurement thresholds fo...
24,1. Project components (see Annex 2 for a detai...,cost analysis,municipal environmental infrastructure,unclear,Croatia,unclear,million DEM,The table reports the costs associated with di...
25,Category\nAmount of the Grant Allocated (expre...,financial allocations,education,unclear,Lebanon,unclear,"USD, percentage",The table reports the amount allocated for var...
26,PRICES and GOVERNMENT FINANCE,statistical data,economics,country-level,Albania,"multiple years (1977, 1987, 1997, 1998)","US$ millions, percentages",The snapshot presents economic indicators for ...
27,4.7 موجز التحليلي (بالدولار الأمريكي),projections,economic analysis,unclear,Djibouti,multi-year trend,thousands of USD,The table presents financial projections relat...
28,Team,administrative counts,education,unclear,unclear,annual,"number of staff weeks, number of trips",The table outlines various expertise needed fo...
29,PDO Indicators by PDO Outcomes,monitoring indicators,social assistance,beneficiaries,unclear,baseline and closing period,number,"This table reports on project beneficiaries, i..."
30,Tajikistan,administrative counts,economics,unclear,country-level,multi-year trend,"US$ millions, percentages",The data reports on various economic indicator...
31,Microcredentials firm contracted\nMicrocredent...,progress indicators,education,secondary education students,Costa Rica,unclear,counts / percentages,The table reports on milestones related to a m...
32,JORDAN COMMUNITY INFRASTRUCTURE PROJECT LOCATI...,administrative counts,infrastructure,squatter settlements,"Greater Amman, Jordan",unclear,geographic locations,The snapshot depicts a map showing the locatio...
33,Table 5: Project Cost and Financing,administrative counts,health,unclear,Iraq,unclear,US$ million,The table outlines the costs and financing sou...
34,Table 1: Implementation Support Table,resource allocation and operational planning,education,unclear,Lebanon,multi-year plan (first twelve months and 12-48...,US$,"The table outlines the timing, focus areas, sk..."