In [1]:
from dsa.utils import load_json
import pandas as pd

In [2]:
preds = load_json("data/unhcr_batch4_backup.json")
preds

[{'id': 484,
  'annotations': [{'id': 156,
    'completed_by': 1,
    'result': [{'id': 'a2ffd1eb',
      'type': 'rectanglelabels',
      'score': 0.9581842422485352,
      'value': {'x': 8.27040363445812,
       'y': 46.65496139457658,
       'width': 81.5093478701042,
       'height': 30.8893316333586,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 3,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '120fff7e',
      'type': 'rectanglelabels',
      'score': 0.9403809309005737,
      'value': {'x': 50.97770319742223,
       'y': 10.88669129974521,
       'width': 40.791333514957685,
       'height': 58.3793701940993,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 4,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '4908293d',
      'type': 'rectanglelabels',
      'score': 0.730929434299469,
      'value': {'x': 8.531860203447666,
       'y': 11.096403390339043,
       'width': 39.935043219431364,
       'height': 59.57174291647915,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 4,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': 'ac67e291',
      'type': 'rectanglelabels',
      'score': 0.9395707845687866,
      'value': {'x': 51.413545401529944,
       'y': 24.748362873396733,
       'width': 39.550066601903694,
       'height': 68.23456142000921,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 5,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': 'c6041958',
      'type': 'rectanglelabels',
      'score': 0.9256072044372559,
      'value': {'x': 8.901863247740504,
       'y': 46.06683563864198,
       'width': 38.09919948203886,
       'height': 42.13120679743753,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 5,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '41bb3dcf',
      'type': 'rectanglelabels',
      'score': 0.9528370499610901,
      'value': {'x': 8.51075043453334,
       'y': 62.33118192190313,
       'width': 68.72054169169216,
       'height': 24.261798665218052,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 6,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '0f90e893',
      'type': 'rectanglelabels',
      'score': 0.946517288684845,
      'value': {'x': 8.594435546495827,
       'y': 10.271410191556257,
       'width': 74.34810756179012,
       'height': 59.922976361356874,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 7,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '03765661',
      'type': 'rectanglelabels',
      'score': 0.9665155410766602,
      'value': {'x': 8.942763811221404,
       'y': 40.65779069362015,
       'width': 81.06235314119064,
       'height': 43.78903257757409,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 8,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '0f846451',
      'type': 'rectanglelabels',
      'score': 0.9200297594070435,
      'value': {'x': 8.554678233936674,
       'y': 49.37147761406999,
       'width': 77.0621040239076,
       'height': 33.656620752407186,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 9,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '78b02baf',
      'type': 'rectanglelabels',
      'score': 0.8333978652954102,
      'value': {'x': 8.724470526240355,
       'y': 69.60327478060316,
       'width': 81.80521386453327,
       'height': 18.84470846987046,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 10,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '6c1215c5',
      'type': 'rectanglelabels',
      'score': 0.35824349522590637,
      'value': {'x': 8.669052263251361,
       'y': 10.014906165909549,
       'width': 78.07636947202306,
       'height': 29.667732300573828,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 10,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '800bfff0',
      'type': 'rectanglelabels',
      'score': 0.9323828220367432,
      'value': {'x': 51.295177864810796,
       'y': 43.86969959202948,
       'width': 39.90007254545535,
       'height': 40.29526548846283,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 11,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300},
     {'id': '7de98030',
      'type': 'rectanglelabels',
      'score': 0.8625995516777039,
      'value': {'x': 8.5837723575178,
       'y': 52.081889731941935,
       'width': 39.388656151130405,
       'height': 31.60834760233818,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 11,
      'image_rotation': 0,
      'original_width': 2550,
      'original_height': 3300}],
    'was_cancelled': False,
    'ground_truth': False,
    'created_at': '2026-04-07T05:49:12.836324Z',
    'updated_at': '2026-04-07T05:49:12.836334Z',
    'draft_created_at': '2026-04-06T14:56:43.501539Z',
    'lead_time': 182.757,
    'prediction': {'id': 71,
     'task': 484,
     'model': None,
     'score': 0.7515793833881617,
     'result': [{'id': 'a2ffd1eb',
       'type': 'rectanglelabels',
       'score': 0.9581842422485352,
       'value': {'x': 15.841749004289216,
        'y': 51.51544744318181,
        'width': 68.57981962316177,
        'height': 26.02884558475379,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 3},
      {'id': '120fff7e',
       'type': 'rectanglelabels',
       'score': 0.9403809309005737,
       'value': {'x': 51.7930788526348,
        'y': 18.89749237985322,
        'width': 39.51002891390932,
        'height': 50.36856911399148,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 4},
      {'id': '4908293d',
       'type': 'rectanglelabels',
       'score': 0.730929434299469,
       'value': {'x': 9.813164804496017,
        'y': 20.547348484848484,
        'width': 34.110931396484375,
        'height': 41.0298887310606,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 4},
      {'id': 'ac67e291',
       'type': 'rectanglelabels',
       'score': 0.9395707845687866,
       'value': {'x': 51.76299211090686,
        'y': 32.57914595170455,
        'width': 38.73469094669119,
        'height': 53.743112275094695,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 5},
      {'id': 'c6041958',
       'type': 'rectanglelabels',
       'score': 0.9256072044372559,
       'value': {'x': 8.901863247740502,
        'y': 54.07763671875,
        'width': 38.09919948203891,
        'height': 34.12040571732955,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 5},
      {'id': '41bb3dcf',
       'type': 'rectanglelabels',
       'score': 0.9528370499610901,
       'value': {'x': 13.403004365808824,
        'y': 66.02155095880681,
        'width': 63.82828776041667,
        'height': 20.571429628314398,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 6},
      {'id': '0f90e893',
       'type': 'rectanglelabels',
       'score': 0.946517288684845,
       'value': {'x': 10.807598039215687,
        'y': 17.832166267163828,
        'width': 57.69114774816176,
        'height': 47.5917432380445,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 7},
      {'id': '03765661',
       'type': 'rectanglelabels',
       'score': 0.9665155410766602,
       'value': {'x': 13.252606560202207,
        'y': 47.40846576112689,
        'width': 72.44266764322916,
        'height': 31.367790453361742,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 8},
      {'id': '0f846451',
       'type': 'rectanglelabels',
       'score': 0.9200297594070435,
       'value': {'x': 16.242505840226716,
        'y': 57.02224269057765,
        'width': 57.376606062346816,
        'height': 26.005855675899625,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 9},
      {'id': '78b02baf',
       'type': 'rectanglelabels',
       'score': 0.8333978652954102,
       'value': {'x': 11.753008674172793,
        'y': 75.6338778409091,
        'width': 73.76793954886642,
        'height': 12.814105409564391,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 10},
      {'id': '6c1215c5',
       'type': 'rectanglelabels',
       'score': 0.35824349522590637,
       'value': {'x': 11.46462593826593,
        'y': 19.01580625591856,
        'width': 14.360586128982844,
        'height': 19.496715198863633,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 10},
      {'id': '323c6366',
       'type': 'rectanglelabels',
       'score': 0.3403211236000061,
       'value': {'x': 49.74763518688726,
        'y': 19.012898763020832,
        'width': 28.65951956954657,
        'height': 19.67333984375,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 10},
      {'id': 'f923b149',
       'type': 'rectanglelabels',
       'score': 0.20996451377868652,
       'value': {'x': 49.92228668811274,
        'y': 18.96564090613163,
        'width': 14.43846698835784,
        'height': 19.61633485736269,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 10},
      {'id': '800bfff0',
       'type': 'rectanglelabels',
       'score': 0.9323828220367432,
       'value': {'x': 54.6731627221201,
        'y': 56.02091471354167,
        'width': 30.115564682904417,
        'height': 28.144050366950758,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 11},
      {'id': '7de98030',
       'type': 'rectanglelabels',
       'score': 0.8625995516777039,
       'value': {'x': 9.282665776271445,
        'y': 64.68314985795455,
        'width': 37.059011421951595,
        'height': 19.007087476325758,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 11},
      {'id': 'ff0cb1cc',
       'type': 'rectanglelabels',
       'score': 0.20778852701187134,
       'value': {'x': 66.52914847579657,
        'y': 52.384329131155305,
        'width': 24.698448031556364,
        'height': 10.874363754734851,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 12}],
     'cluster': None,
     'project': 47,
     'model_run': None,
     'neighbors': None,
     'created_at': '2026-04-06T14:06:42.679139Z',
     'updated_at': '2026-04-06T14:06:42.679144Z',
     'created_ago': '15\xa0hours, 42\xa0minutes',
     'mislabeling': 0.0,
     'model_version': 'undefined'},
    'result_count': 13,
    'unique_id': 'bea8ec90-3818-41ce-99f7-b2ca1db27273',
    'import_id': None,
    'last_action': None,
    'bulk_created': False,
    'task': 484,
    'project': 47,
    'updated_by': 1,
    'parent_prediction': None,
    'parent_annotation': None,
    'last_created_by': None}],
  'drafts': [],
  'predictions': [71],
  'data': {'pages': ['/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p000.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p001.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p002.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p003.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p004.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p005.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p006.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p007.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p008.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p009.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p010.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p011.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p012.png',
    '/data/local-files/?d=unhcr_batch4/unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf_p013.png']},
  'meta': {'file': 'unhcr-unw_disability_and_women_and_girls_in_displacement_from_myanmar.pdf'},
  'created_at': '2026-04-06T14:06:42.650045Z',
  'updated_at': '2026-04-07T05:49:12.903698Z',
  'allow_skip': True,
  'inner_id': 2,
  'total_annotations': 1,
  'cancelled_annotations': 0,
  'total_predictions': 1,
  'comment_count': 0,
  'unresolved_comment_count': 0,
  'last_comment_updated_at': None,
  'project': 47,
  'updated_by': 1,
  'comment_authors': []},
 {'id': 485,
  'annotations': [{'id': 157,
    'completed_by': 1,
    'result': [{'id': '695595a2',
      'type': 'rectanglelabels',
      'score': 0.8973420858383179,
      'value': {'x': 14.07709816780687,
       'y': 65.88006061179921,
       'width': 37.45310169026247,
       'height': 23.85076557469616,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 0,
      'image_rotation': 0,
      'original_width': 2480,
      'original_height': 3509},
     {'id': 'b9d093a8',
      'type': 'rectanglelabels',
      'score': 0.9047563672065735,
      'value': {'x': 14.76919123632236,
       'y': 13.475399770190139,
       'width': 72.12702564445391,
       'height': 17.322642483064083,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 1,
      'image_rotation': 0,
      'original_width': 2480,
      'original_height': 3509},
     {'id': 'f8b2c590',
      'type': 'rectanglelabels',
      'score': 0.5145472884178162,
      'value': {'x': 14.708714651170524,
       'y': 65.04925800549286,
       'width': 72.06334490853729,
       'height': 24.553320041362213,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 1,
      'image_rotation': 0,
      'original_width': 2480,
      'original_height': 3509},
     {'id': '9d605b3c',
      'type': 'rectanglelabels',
      'score': 0.8704925775527954,
      'value': {'x': 14.817895039473427,
       'y': 72.07660908779212,
       'width': 72.0336051582718,
       'height': 10.195189647479058,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 4,
      'image_rotation': 0,
      'original_width': 2480,
      'original_height': 3509},
     {'id': 'b679f1b3',
      'type': 'rectanglelabels',
      'score': 0.7980573773384094,
      'value': {'x': 14.758147035913701,
       'y': 29.86209469056231,
       'width': 35.40638574279182,
       'height': 17.398880871262104,
       'rotation': 0,
       'rectanglelabels': ['Figure']},
      'origin': 'prediction-changed',
      'to_name': 'pdf',
      'from_name': 'rectangles',
      'item_index': 4,
      'image_rotation': 0,
      'original_width': 2480,
      'original_height': 3509}],
    'was_cancelled': False,
    'ground_truth': False,
    'created_at': '2026-04-07T06:12:49.487065Z',
    'updated_at': '2026-04-07T06:12:49.487083Z',
    'draft_created_at': '2026-04-07T06:10:49.139467Z',
    'lead_time': 133.808,
    'prediction': {'id': 72,
     'task': 485,
     'model': None,
     'score': 0.626097165621244,
     'result': [{'id': '695595a2',
       'type': 'rectanglelabels',
       'score': 0.8973420858383179,
       'value': {'x': 14.713875555223035,
        'y': 66.2400966153997,
        'width': 34.2692147531817,
        'height': 23.220702568395545,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 0},
      {'id': '3c679b43',
       'type': 'rectanglelabels',
       'score': 0.40242236852645874,
       'value': {'x': 36.402482063539566,
        'y': 4.367604205397059,
        'width': 25.571424422725553,
        'height': 3.456374891601284,
        'rotation': 0,
        'rectanglelabels': ['Figure']},
       'to_name': 'pdf',
       'from_name': 'rectangles',
       'item_index': 0},
      {'id': 'b9d093a8',
       'type': 'rectanglelabels',
       'score': 0.9047563672065735,
       'value': {'x': 15.15125766877205,
        'y': 13.655417771990328,
        'width': 70.98082634710497,

In [3]:
results = []
for x in range(len(preds)):
    annot = preds[x]["annotations"][0]
    for y in annot["result"]:
        results.append(y)

In [4]:
len(results)

329

In [5]:
results[0]

{'id': 'a2ffd1eb',
 'type': 'rectanglelabels',
 'score': 0.9581842422485352,
 'value': {'x': 8.27040363445812,
  'y': 46.65496139457658,
  'width': 81.5093478701042,
  'height': 30.8893316333586,
  'rotation': 0,
  'rectanglelabels': ['Figure']},
 'origin': 'prediction-changed',
 'to_name': 'pdf',
 'from_name': 'rectangles',
 'item_index': 3,
 'image_rotation': 0,
 'original_width': 2550,
 'original_height': 3300}

In [6]:
norm_areas = {}
for x in results:
    try:
        # if x["origin"] in ["prediction-changed", "manual"]:
        width = x["value"]["width"]
        height = x["value"]["height"]
        o_width = x["original_width"]
        o_height = x["original_height"]

        id = x["id"]
        na = (width * height) / (o_width * o_height)
        norm_areas[id] = na
    except:
        continue

In [7]:
df = pd.DataFrame.from_dict(norm_areas, orient="index", columns=["norm_area"]).reset_index()

df

        index  norm_area
0    a2ffd1eb   0.000299
1    120fff7e   0.000283
2    4908293d   0.000283
3    ac67e291   0.000321
4    c6041958   0.000191
..        ...        ...
320  daa237eb   0.000091
321  0435b0c0   0.000158
322  34a415c4   0.000259
323  019f70e5   0.000188
324  459a6156   0.000056

[325 rows x 2 columns]

In [8]:
df[df["norm_area"] < 0.00002]

          index  norm_area
244  3WAD92GU7b   0.000018